-- CreateTable
CREATE TABLE "budget" (
    "id" SERIAL NOT NULL,
    "SETBUDGET" DOUBLE PRECISION NOT NULL,
    "FINANCIALYEAR" TEXT NOT NULL,
    "BUDGETEDCOUNTY" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "budget_pkey" PRIMARY KEY ("id")
);
